# Site settings
title: No Leas Este Blog
subtitle: hemos tratado de avisarte
email: valiente@noleasesteblog.com
description: Aprender, descubrir y compartir los libros que leemos.
baseurl: "/noleasesteblog.com"
url: "http://noleasesteblog.com"

# Build settings
markdown: kramdown
permalink: :title

sass:
  sass_dir: assets/_sass
  style: :compressed
